In [1]:
import numpy as np

In [2]:
#Delivery fee is calculated using a different method for each branch. The fee depends linearly (but in different ways for each branch) on:
#a. weekend or weekday (1 or 0) - as a continuous variable
#b. time of the day (morning 0, afternoon 1, evening 2) - as a continuous variable
#c. distance between branch and customer*
#If a customer has loyalty, they get a 50% discount on the delivery fee

In [16]:
#values from NS branch
#1x + 1y + 7.906z = 13.2158734
#0x + 0y + 7.169z = 12.6752781
#0x + 2y + 8.545z = 15.1975901

A = np.array([[1,1,7.906],[0,0,7.169],[0,2,8.545]])
print(A)
b = np.array([13.2158734,12.6752781,15.1975901])
print(b)
results = np.linalg.solve(A,b)
print(results)

[[1.    1.    7.906]
 [0.    0.    7.169]
 [0.    2.    8.545]]
[13.2158734 12.6752781 15.1975901]
[-0.80719602  0.04472535  1.76806781]


In [17]:
-0.80719602*0 + 0.04472535*2 + 1.76806781*6.538

11.649078041780001

In [18]:
#here i tested the results of solving the linear system of equations for 3 sets of values from the NS branch. 
#however, i discovered that the coefficients are not independant and hence do not allow for calculation of missing values.
